declare type MapDataLine = {
    nameRU: string;
    regions: string;
    types: string;
    apps: string;
};
declare const indexPageUrlRu: string;
declare const indexPageUrlEn: string;
declare const russianPagesPostfix: string;
declare const englishPagesPostfix: string;
declare const contactsPageUrlRu: string;
declare const contactsPageUrlEn: string;
declare function redirectToIndexPage(): void;
declare function redirectToContactsPage(): void;
declare function redirectToPageWithAnotherLanguage(): void;
declare let isInDownloadingMode: boolean;
declare const regularModeHeaderID = "regularModeHeader";
declare const downloadingHeaderID = "downloadModeHeader";
declare const regularModeButtonID = "downloadMenuListBtn";
declare const downloadingModeButtonID = "downloadMenuBackBtn";
declare const rubricatorID = "rubricator";
declare function changeMenuMode(): void;
declare function showCorrectUiForCurrentMode(): void;
declare const defaultSelectorValue = 0;
declare const countrySelectID = "mapCountrySelector";
declare const categorySelectID = "mapCategorySelector";
declare const appSelectID = "mapAppSelector";
declare function resetAllSelectElements(): void;
declare function setSelectElementWith(value: number, id: string): void;
declare function setAppTypeFromUrlParams(): void;
declare const defaultValue = "All";
declare const globalCoverageValue = "World";
declare let currentRegion: string;
declare let currentType: string;
declare let currentApp: string;
declare function changeRegion(newValue: string): void;
declare function changeType(newValue: string): void;
declare function changeApp(newValue: string): void;
declare const allCountriesValue = "World";
declare const replacingDivClass = "replacing_div";
declare let downloadedMapList: MapDataLine[];
declare function updateMapList(): void;
declare function generateMapListHtml(mapListItems: MapDataLine[]): void;
declare const mapLineTemplate = "\n<br>\n\n<div class=\"mapLine\">\n<!--    <input type=\"checkbox\" class=\"mapLineCheckbox\">-->\n\n    <a class=\"mapLinePreview\"\n        href=\"https://anygis.ru/api/v1/preview/{anygisMapName}\"\n        target=\"_blank\" title=\"\u041F\u0440\u0435\u0434\u043F\u0440\u043E\u0441\u043C\u043E\u0442\u0440 \u043A\u0430\u0440\u0442\u044B\">\n        <img src=\"/Web/Img/eye_gray.png\" class=\"eye_icon\"/>\n    </a>\n    \n    <a class=\"mapLineLink\"\n        href=\"{singleMapDownloadUrl}\"\n        title=\"\u0421\u043A\u0430\u0447\u0430\u0442\u044C \u044D\u0442\u0443 \u043A\u0430\u0440\u0442\u0443\">\n        {mapName}\n    </a>\n</div>\n\n    ";
declare function replaceElementContent(elementClass: string, newContent: string): void;
declare function getCurrentURL(): string;
declare function getQueryVariable(variable: string): string;
declare function redirectTo(url: string): void;
declare function isContains(sourceText: string, checkingText: string): boolean;
declare function setDivVisiability(className: string, isVisible: boolean): void;
declare function downloadMapList(): MapDataLine[];
//# sourceMappingURL=AGScripts.d.ts.map